version: "3.7"

services:
  food-db:
    image: postgres:14.7-alpine
    ports:
      - "5432:5432"
    volumes:
      - food-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: food_graph
      POSTGRES_USER: food_graph
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U food_graph" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  food-db-data:
    driver: local
