version: "3.7"

services:
  food-db:
    extends:
      file: docker-compose.services.yml
      service: food-db

  food-app:
    build: .
    container_name: food-graph
    environment:
      DB_URL: postgresql+asyncpg://food_graph:password@food-db/food_graph
    links:
      - food-db
    depends_on:
      food-db:
        condition: service_healthy
    ports:
      - "8000:8000"
    expose:
      - "8000"
    healthcheck:
      test: [ "CMD-SHELL", "curl", "http://localhost:8000/rest/health" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  food-db-data:
    driver: local
