"""add recipes

Revision ID: 130dcff57c4d
Revises: 67955fad8437
Create Date: 2023-05-18 15:27:33.578832+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '130dcff57c4d'
down_revision = '67955fad8437'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('recipe_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dish_ingredients', sa.Column('recipe_ingredient_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('dish_ingredients_recipe_ingredients', 'dish_ingredients', 'recipe_ingredients', ['recipe_ingredient_id'], ['id'])
    op.add_column('dishes', sa.Column('recipe_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('dishes', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('dishes_recipes', 'dishes', 'recipes', ['recipe_id'], ['id'])
    op.create_foreign_key('dishes_users', 'dishes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dishes_recipes', 'dishes', type_='foreignkey')
    op.drop_constraint('dishes_users', 'dishes', type_='foreignkey')
    op.drop_column('dishes', 'user_id')
    op.drop_column('dishes', 'recipe_id')
    op.drop_constraint('dish_ingredients_recipe_ingredients', 'dish_ingredients', type_='foreignkey')
    op.drop_column('dish_ingredients', 'recipe_ingredient_id')
    op.drop_table('recipe_ingredients')
    op.drop_table('recipes')
    # ### end Alembic commands ###
