"""revision

Revision ID: dbb72f045cb9
Revises: 130dcff57c4d
Create Date: 2024-02-26 10:36:45.844760+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbb72f045cb9'
down_revision = '130dcff57c4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='concrete'
    )
    op.create_table('cars',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='joint'
    )
    op.create_table('cars',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='joint_magic'
    )
    op.create_table('cars',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='naive'
    )
    op.create_table('cars',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='poly_object'
    )
    op.create_table('cars',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='single'
    )
    op.create_table('cars',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='single_magic'
    )
    op.create_table('car_doors',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('door_type', sa.String(length=256), nullable=True),
    sa.Column('car_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['concrete.cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='concrete'
    )
    op.create_table('car_wheels',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('wheel_size', sa.Integer(), nullable=True),
    sa.Column('car_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['concrete.cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='concrete'
    )
    op.create_table('car_details',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('car_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['joint.cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='joint'
    )
    op.create_table('car_details',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('car_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['joint_magic.cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='joint_magic'
    )
    op.create_table('car_doors',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('door_type', sa.String(length=256), nullable=True),
    sa.Column('car_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['naive.cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='naive'
    )
    op.create_table('car_wheels',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('wheel_size', sa.Integer(), nullable=True),
    sa.Column('car_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['naive.cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='naive'
    )
    op.create_table('car_details',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('car_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['poly_object.cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='poly_object'
    )
    op.create_table('car_details',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('door_type', sa.String(length=256), nullable=True),
    sa.Column('wheel_size', sa.Integer(), nullable=True),
    sa.Column('car_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['single.cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='single'
    )
    op.create_table('car_details',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('car_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('wheel_size', sa.Integer(), nullable=True),
    sa.Column('door_type', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['single_magic.cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='single_magic'
    )
    op.create_table('car_doors',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('car_detail_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('door_type', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['car_detail_id'], ['joint.car_details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='joint'
    )
    op.create_table('car_wheels',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('car_detail_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('wheel_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_detail_id'], ['joint.car_details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='joint'
    )
    op.create_table('car_doors',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('door_type', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['joint_magic.car_details.id'], ),
    schema='joint_magic'
    )
    op.create_table('car_wheels',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('wheel_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['joint_magic.car_details.id'], ),
    schema='joint_magic'
    )
    op.create_table('car_doors',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('door_type', sa.String(length=256), nullable=True),
    sa.Column('car_detail_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['car_detail_id'], ['poly_object.car_details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='poly_object'
    )
    op.create_table('car_wheels',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('wheel_size', sa.Integer(), nullable=True),
    sa.Column('car_detail_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['car_detail_id'], ['poly_object.car_details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='poly_object'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_wheels', schema='poly_object')
    op.drop_table('car_doors', schema='poly_object')
    op.drop_table('car_wheels', schema='joint_magic')
    op.drop_table('car_doors', schema='joint_magic')
    op.drop_table('car_wheels', schema='joint')
    op.drop_table('car_doors', schema='joint')
    op.drop_table('car_details', schema='single_magic')
    op.drop_table('car_details', schema='single')
    op.drop_table('car_details', schema='poly_object')
    op.drop_table('car_wheels', schema='naive')
    op.drop_table('car_doors', schema='naive')
    op.drop_table('car_details', schema='joint_magic')
    op.drop_table('car_details', schema='joint')
    op.drop_table('car_wheels', schema='concrete')
    op.drop_table('car_doors', schema='concrete')
    op.drop_table('cars', schema='single_magic')
    op.drop_table('cars', schema='single')
    op.drop_table('cars', schema='poly_object')
    op.drop_table('cars', schema='naive')
    op.drop_table('cars', schema='joint_magic')
    op.drop_table('cars', schema='joint')
    op.drop_table('cars', schema='concrete')
    # ### end Alembic commands ###
