"""revision

Revision ID: cbbf7de4443f
Revises: 130dcff57c4d
Create Date: 2024-02-26 12:34:39.033339+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbbf7de4443f'
down_revision = '130dcff57c4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='joint_magic'
    )
    op.create_table('cars',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='single_magic'
    )
    op.create_table('car_details',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('car_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['joint_magic.cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='joint_magic'
    )
    op.create_table('car_details',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('car_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('wheel_size', sa.Integer(), nullable=True),
    sa.Column('door_type', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['single_magic.cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='single_magic'
    )
    op.create_table('car_doors',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('door_type', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['joint_magic.car_details.id'], ),
    schema='joint_magic'
    )
    op.create_table('car_wheels',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('wheel_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['joint_magic.car_details.id'], ),
    schema='joint_magic'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_wheels', schema='joint_magic')
    op.drop_table('car_doors', schema='joint_magic')
    op.drop_table('car_details', schema='single_magic')
    op.drop_table('car_details', schema='joint_magic')
    op.drop_table('cars', schema='single_magic')
    op.drop_table('cars', schema='joint_magic')
    # ### end Alembic commands ###
